Bugfix: svg 的顏色有誤
iCHEF/gypcrete pull request #285
Opened 2020-08-24 09:26 UTC by benny0642

# Purpose

過去還是 font icon 時，font icon 滿多都是吃是上層 component 的 css `color` property 來顯示顏色，譬如上層有 `gyp-state-error`，那麼 font icon 就顯示紅色。但我們現在改成 svg icon 了，svg 不吃 `color` property，所以顏色就錯了。

Before(no error):
![截圖 2020-08-24 下午5 23 20](https://user-images.githubusercontent.com/9179190/91027400-a2a7a000-e62e-11ea-8ae0-28aa97e8a5e2.png)

After(with error):
![截圖 2020-08-24 下午5 23 27](https://user-images.githubusercontent.com/9179190/91027448-b226e900-e62e-11ea-81fe-c833e5b143ac.png)

**感謝主席！讚嘆主席！**，我們補上了 `fill: currentColor` 就解了。

# Changes

- a list of what have been done
- maybe some code change

# Risk

Usually none, if you have any please write it here.

2020-08-24 09:43 UTC, kyoyadmoon approved these changes

2020-08-24 09:56 UTC, chenesan approved these changes

2020-08-25 02:58 UTC, zhusee2 approved these changes

2020-08-25 03:46 UTC, zhusee2 requested changes
對於有些 svg 裡面寫死 fill 的來說，這招就無用了
要換個方法，可以考慮下面兩種

- https://react-svgr.com/docs/options/#replace-attribute-value
- https://react-svgr.com/docs/custom-transformations/

2020-08-25 08:22 UTC, zhusee2 approved these changes
![](https://media3.giphy.com/media/3o7btMotAhVnUOz2Mg/giphy.gif?cid=5a38a5a20p6dqfvo0acxgqjyq54cdlnt3p61le68awzj1h02&rid=giphy.gif)

2020-08-25 08:35 UTC, chenesan approved these changes

2020-08-25 08:39 UTC, tz5514 approved these changes
強

2020-08-25 08:39 UTC, tz5514 commented on packages/core/src/Icon.js
> +            {SvgComponent && <SvgComponent fill={fill || DEFAULT_FILL} {...svgProps} />}
```suggestion
            {...otherProps}
        >
            {SvgComponent && (
              <SvgComponent fill={fill || DEFAULT_FILL} {...svgProps} />
            )}
```

2020-08-25 08:59 UTC, merged